# 备份服务配置
server:
  # 服务器基本配置
  bind-address: "0.0.0.0"  # 监听地址
  bind-port: 8101         # 监听端口
  mode: "release"          # 运行模式:debug/release
  
# MongoDB配置
mongo:
  host: localhost
  port: 27017
#  username: admin
#  password: admin
  database: wechat_backup

# Redis配置  
redis:
  host: localhost
  port: 6379
  password: ""          # Redis密码,无密码则留空
  db: 0                 # 使用的数据库编号

log:
  name: wx-backup # Logger name
  development: true # 是否是开发模式。如果是开发模式，会对DPanicLevel进行堆栈跟踪。
  level: debug # 日志级别，优先级从低到高依次为：debug, info, warn, error, dpanic, panic, fatal。
  format: console # 支持的日志输出格式，目前支持console和json两种。console其实就是text格式。
  enable-color: true # 是否开启颜色输出，true:是，false:否
  disable-caller: false # 是否开启 caller，如果开启会在日志中显示调用日志所在的文件、函数和行号
  disable-stacktrace: false # 是否再panic及以上级别禁止打印堆栈信息